# Generated by Django 5.2.6 on 2025-09-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('pet_type', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака'), ('bird', 'Птица'), ('rodent', 'Грызун'), ('reptile', 'Рептилия'), ('fish', 'Рыба'), ('other', 'Другое')], max_length=20, verbose_name='Тип животного')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Вес (в граммах)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='В наличии')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pet_food/', verbose_name='Фото упаковки')),
            ],
        ),
    ]
