# Generated by Django 5.2.6 on 2025-09-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_zoo', '0003_product_delete_petfood_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_zoo.category', verbose_name='Категория'),
        ),
    ]
